Use env variables as input alternative
shiftavenue/gas-action pull request #30
Opened 2024-12-29 01:43 UTC by leblonk

This will allow the action to be used from gitlab

2025-01-09 15:24 UTC, relusc requested changes

2025-01-09 15:24 UTC, relusc commented on pkg/config/config.go
> +    if ( command == "" ) {
```suggestion
    if command == "" {
```

brackets are not needed ;)

2025-01-09 16:33 UTC, leblonk commented on pkg/config/config.go
> +    if ( command == "" ) {
I removed them. Go novice :)

2025-01-10 06:46 UTC, relusc approved these changes

2025-01-10 06:51 UTC, merged